### ISSUE TITLE
Anti-warmonger license?!

### ISSUE THREAD

**Issue by perguth** [infuanfu/meta#4]
> Vielleicht hört mir jetzt endlich jemand zu, wenn ich sage, dass wir bei Lizenzen für freie Software eine Klausel gegen Militär und Geheimdienste brauchen? http://blog.fefe.de/?ts=ab6887a1

Ihr hattet doch da etwas geschrieben?! @bronsen

**Comment by bronsen** [comment]
Right here: https://github.com/infuanfu/NMHL

**Comment by perguth** [comment]
Ah, thanks!
