### ISSUE TITLE
Also exclude sith padawans

### ISSUE THREAD

**Issue by perguth** [infuanfu/meta#5]
Eg. `Hacking Team`. They should not be allowed to use our softare and I hope they now get sued like crazy by their clients for not opening up their product source code (it seems they built upon GPL'ed software): https://www.schneier.com/blog/archives/2015/07/hacking_team_is.html

**Comment by perguth** [comment]
On that mark I propose a "beeing a Jedi" requirement like so: http://pguth.github.io/jedi_commons/ :satisfied:

That could be a fun clause that does not impair the rest of the license (I guess all the common licenses use salvatorius clauses nowadays).

**Comment by perguth** [comment]
I am talking about https://github.com/infuanfu/NMHL of course (no issue tracker enabled there).

**Comment by hdznrrd** [comment]
:-1: to jedi, let's stay focused pleased
:-1: to hackingteam, FWIW a case like this is already covered by the surveillance clause

**Comment by hdznrrd** [comment]
I did enable issues on NHML though, thanks for the pointer

**Comment by perguth** [comment]
> :-1: to jedi, let's stay focused pleased

You're the boss, man.

> :-1: to hackingteam, FWIW a case like this is already covered by the surveillance clause

Ah, great. Yeah, for what it's worth... at least we tried.
