### ISSUE TITLE
bronsen packliste

### ISSUE THREAD

**Issue by bronsen** [infuanfu/meta#6]
- [x] 12+ T-Shirts
- [x] U-Hosen
- [x] n paar Socken
- [x] 1 lange Hose (die wo am besten passt)
- [x] 1 Hoodie
- [x] 1 paar feste, geschlossene Schuhe
- [x] Sandalen
- [x] Sonnenbrillen
- [x] Sonnencreme
- [x] Zahnbürste
- [x] Zahnpasta
- [x] Zahnseide
- [x] Mundwasser
- [x] Nagelfeile
- [x] Nagelklipser
- [x] Taschentücher
- [x] 2 große Badetücher
- [x] 2 kleine Handtücher
- [x] Schutzbrille
- [x] Schutzhandschuhe
- [x] kindle
- [x] Ladegerät für Kindle
- [x] Fotoapperat mit Zubehör (Akkus, Speicherkarten, Reinigungsset)
- [x] alle drei Objektive
- [x] Selfie-Stick
- [x] Ladegerät für Foto
- [x] Duschgel
- [x] Badeschlappen
- [x] Rasierapperat
- [x] Rasierklingen
- [x] Rasierseife
- [x] 2 kurze Hosen
- [x] Laken zum zudecken
- [x] Bettbezug zum zudecken und ggfs Decke beziehen
- [x] Leselampe
- [x] Kuscheltiere
- [x] USB-Sticks
- [x] Laptop
- [x] Netzteil für Laptop
- [x] Adapter für Netzteil für Laptop
- [x] Displayport-Adapter
- [x] Smartphone
- [x] Infuanfu-pins
- [x] Kopfhörer
- [x] 1 Satz Postits
- [x] Aftershave
- [x] Kissen
- [x] Seitenschläferkissen
- [x] Camp tickets (per se + swag)
- [x] Führerschein
- [x] Metrokarte
- [x] Halzbonbon
- [x] Bronchicum-Tropfen
- [x] Ibuprofen
- [x] Gaskartuschen
- [x] Gaskartuschenwerkzeug
- [x] Fototasche
- [x] Rucksack
- [x] Badehose

**Comment by bronsen** [comment]
- [ ] Camp tickets (per se + swag)
- [ ] Führerschein
- [ ] Metrokarte
- [ ] Halzbonbon
- [ ] Bronchicum-Tropfen
- [ ] Ibuprofen
- [ ] Gaskartuschen
- [ ] Gaskartuschenwerkzeug
- [ ] Fototasche
- [ ] Rucksack
- [ ] ...

**Comment by pguth** [comment]
:+1:
