### ISSUE TITLE
Ordentlichen e.V. gründen

### ISSUE THREAD

**Issue by hdznrrd** [infuanfu/meta#8]
Das infuanfu soll als ordentlicher e.V. neu gründen werden.
Gemeinnützigkeit ist nicht angestrebt aber soll als Möglichkeit für die Zukunft offen gehalten werden.
Anlass: Anmietung eigener Räume in absehbarer Zukunft und dafür sinnvolle Herstellung von Geschäftsfähigkeit.

Angedacht ist ein verwaltender e.V. mit effektiv fixem Minimalvorstand.
Die Mehrheit der Mitglieder sollen Fördermitglieder ohne Stimmrecht sein.
Der Verwaltungsappart soll weitgehend automatisiert werden (incl. Sitzungsprotokollen, Buchführung, Mitgliederverwaltung,...).
Weiterhin soll Beschlussfassung (ausserhalb einer Mitgliederversammlung) im Tagesgeschäft wie gewohnt über Issues (o.ä.) durch alle Mitglieder getätigt werden.

Es sollen Mitgliedsbeiträge erhoben werden um laufende Kosten (primär Raummiete, Nebenkosten, Verwaltungskosten) zu decken.
Aktuelle Planung beläuft sich auf ~400 €/Monat.

Im beschränkten Umfang sollen Neumitglieder vorgeschlagen werden.
Hierzu gilt das gleiche Prinzip wie bisher: bestehende Mitglieder entscheiden über die Aufnahme neuer Mitglieder.

Zum Zeitpunkt der Gründung sind 7 Mitglieder notwendig.
Davon können alle bis auf den Vorstand ggf wieder austreten.

**Comment by bronsen** [comment]
hier hat der bronsen mal sowas wie seine Vision oder Vorstellung aufgeschrieben: https://pads.ccc.de/PFcxfphJ8b 

Das ist noch im Fluss; was aber bleiben wird: das infuanfu ist exklusiv bis elitär und das mit Absicht.

**Comment by hdznrrd** [comment]
ergänzt um dies:
     - Mitglieder sind per default Fördermitglieder (kein Stimmrecht auf MV) damit lässt sich der Vereinsteil vollautomatisieren (./omv.sh). Generell soll so viel wie möglich der lästigen Vereinsfoos automatisiert werden.

**Comment by bronsen** [comment]
im prinzip done: fehlt nur noch Notar und Gericht und dann Bank und Mietvertrach und mitgliedsbeiträge

**Comment by bronsen** [comment]
## Statusupdate
- Der Notar muss noch bevollmächtigt werden
- Dann kann auch endlich das Bankkonto eröffnet werden
